global:
  wire_format: "csv"
  fog_addr: ":10000"

gateways:
  - id: "GW01"
    lora_device: "/tmp/ttyV1"
    lora_baud: 9600
    vehicles: ["V01"]
    wire_in: "csv" # format nhận từ vehicle
    wire_out: "json" # format gửi lên fog
    fog_url: "http://127.0.0.1:10000"
  - id: "GW02"
    lora_device: "/tmp/ttyV2"
    lora_baud: 9600
    vehicles: ["V02"]
    wire_in: "csv" # format nhận từ vehicle
    wire_out: "csv" # format gửi lên fog
    fog_url: "http://127.0.0.1:10000"

vehicles:
  - id: "V01"
    lora_device: "/tmp/ttyV11"
    lora_baud: 9600
    gps_device: "/tmp/ttyV12"
    gps_baud: 9600
    telemetry_interval_ms: 2000
    wire_format: "csv"
  - id: "V02"
    lora_device: "/tmp/ttyV21"
    lora_baud: 9600
    gps_device: "/tmp/ttyV22"
    gps_baud: 9600
    telemetry_interval_ms: 4000
    wire_format: "csv"
